language: cpp

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - libboost-all-dev
    - libgtest-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - gcc -v
  - make
  - make test
