language: cpp

compiler:
  - gcc
  - clang

os: linux
dist: xenial

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7

install:
  - wget https://dl.bintray.com/boostorg/release/1.68.0/source/boost_1_68_0.tar.gz
  - tar xzf boost_1_68_0.tar.gz

before_script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_CXX_COMPILER=g++-7 -DBOOST_ROOT=./boost_1_68_0

script:
  - gcc -v
  - make -j 2
  - make test
